name: Deploy
on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  push:
    branches: [main]
  workflow_dispatch: # Manual trigger

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-http-header-size=16384"
      # Add these to help with feed fetching
      UV_THREADPOOL_SIZE: "64"
      FETCH_RETRY_COUNT: "5"
      FETCH_TIMEOUT: "30000"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Test Substack feeds
        run: |
          echo "Testing Substack feeds with curl..."
          curl -v -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" \
               -H "Accept: application/rss+xml, application/xml, text/xml, application/atom+xml" \
               -H "Accept-Language: en-US,en;q=0.9" \
               -H "Cache-Control: no-cache" \
               -H "Pragma: no-cache" \
               -H "Sec-Fetch-Dest: document" \
               -H "Sec-Fetch-Mode: navigate" \
               -H "Sec-Fetch-Site: none" \
               -H "Sec-Fetch-User: ?1" \
               --connect-timeout 20 \
               --max-time 30 \
               --retry 3 \
               --retry-delay 5 \
               --retry-max-time 60 \
               https://theunderlying.substack.com/feed > substack_test.xml
          echo "Substack feed content:"
          cat substack_test.xml

      - name: Fetch new feeds
        run: |
          # Add delay between retries
          sleep 3
          npm run refresh

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Commit feed updates
        run: |
          git add src/content/feeds/
          git diff --staged --quiet || (git commit -m "Update feeds" && git push)

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
